// flow-typed signature: 2d28e0e2a24c611b3d1a9e8b335b4e61
// flow-typed version: <<STUB>>/chart.js_v^2.8.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chart.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chart.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chart.js/dist/Chart.bundle' {
  declare module.exports: any;
}

declare module 'chart.js/dist/Chart.bundle.min' {
  declare module.exports: any;
}

declare module 'chart.js/dist/Chart' {
  declare module.exports: any;
}

declare module 'chart.js/dist/Chart.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chart.js/dist/Chart.bundle.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart.bundle'>;
}
declare module 'chart.js/dist/Chart.bundle.min.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart.bundle.min'>;
}
declare module 'chart.js/dist/Chart.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart'>;
}
declare module 'chart.js/dist/Chart.min.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart.min'>;
}
